### PR TITLE
Revert to shading CommandAPI

### PR DESCRIPTION
**Pull request by spazzylemons**
**Is your feature request related to a problem? Please describe.**
StickyCommands does not work currently. CommandAPI cannot be loaded by the plugin.

**Describe the solution you'd like**
Reverting to shading CommandAPI and disabling the CommandAPI plugin should work.

**Additional context**
I can't figure out how to build this locally, some help would be appreciated in that regard

### CODE REVIEW

**Comment by ZachyFoxx** [comment]
Can you to into more detail on this please.

Also, you are required to call the onload and enable methods when you use the shaded commandapi

**Comment by spazzylemons** [comment]
More specifically, when using commandapi-core, an IllegalAccessError occurs and the plugin does not load. This is causing major issues such as placeholders not resolving.

```
[23:29:25 ERROR]: Error occurred while enabling StickyCommands v4.2.0 (Is it up to date?)
java.lang.IllegalAccessError: class dev.jorel.commandapi.CommandAPICommand tried to access method 'void dev.jorel.commandapi.CommandAPIHandler.register(java.lang.String, dev.jorel.commandapi.CommandPermission, java.lang.String[], java.util.function.Predicate, java.util.List, dev.jorel.commandapi.CustomCommandExecutor, boolean)' (dev.jorel.commandapi.CommandAPICommand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6146edd9; dev.jorel.commandapi.CommandAPIHandler is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3158169c)
        at dev.jorel.commandapi.CommandAPICommand.register(CommandAPICommand.java:480) ~[?:?]
        at com.dumbdogdiner.stickycommands.util.sticky.StickyStartupUtil.registerCommands(StickyStartupUtil.kt:39) ~[?:?]
        at com.dumbdogdiner.stickycommands.StickyCommands.onEnable(StickyCommands.kt:68) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1016]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1016]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1016]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1016]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1016]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470) ~[patched_1.16.5.jar:git-Purpur-1016]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:253) ~[patched_1.16.5.jar:git-Purpur-1016]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:949) ~[patched_1.16.5.jar:git-Purpur-1016]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1016]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

Thanks for the tip on loading CommandAPI when shading, I forgot about that

**Comment by spazzylemons** [comment]
Added .onLoad and .onEnable, seems to work fine now

**Review by ZachyFoxx — APPROVED** [review]
I'm truly upset this did not work in production as expected, but oh well, we can figure this out later.

**Pull request merged**
